/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hoss.game;


import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AppApplicationTests {

  @Test
  void contextLoads() {
  }

}